### ISSUE TITLE
Can I run it with non-model reference genomes?

### ISSUE THREAD

**Issue by DuttaAnik** [bekirsch/HaploBlocks#4]
Hi, thank you for developing this tool. I would be interested to run it on my samples. I have a reference genome that is scaffolded only. So, the chromosome identifiers are not the same as you mentioned in the manual. Also, I do not have the genetic map (recombination map) in cM. I can create a map file from the existing VCF file. Will that work in this case? As I have different population genetic clusters, should I run this for each genetic cluster separately and for each chromosome separately as it is done in other Selection scan tools?

Please let me know. Thank you.

**Comment by bekirsch** [comment]
Hi DuttaAnik,

thank you for your interest in our tool.

> I have a reference genome that is scaffolded only. So, the chromosome identifiers are not the same as you mentioned in the manual.

HaploBlocks works with any chromosome name. By default, the tool tries to retrieve the chromosome number from the file. If it is not possible to get the information, a message will be displayed stating that the chromosome number could not be retrieved from the file.

> Also, I do not have the genetic map (recombination map) in cM. I can create a map file from the existing VCF file. Will that work in this case?

The genetic map is essential for our method. If you don't have one, you could assume a constant recombination rate per base pair and generation, but that would merely be an approximation.

> As I have different population genetic clusters, should I run this for each genetic cluster separately and for each chromosome separately as it is done in other Selection scan tools?

As long as these clusters are part of a (meta) population, you can analyze them together. One of the advantages of HaploBlocks is that it can deal with population structure.

Best
Bene
