### ISSUE TITLE
value "--N_e 2e4"

### ISSUE THREAD

**Issue by yunhanajing** [bekirsch/HaploBlocks#5]
I am curious about the reasoning behind the value "--N_e 2e4" mentioned in the README.md where examples are presented. Could you please provide an explanation for how this value was determined?

**Comment by bekirsch** [comment]
Hi yunhanajing,
thank you for your interest in our tool! 2e4 is two times (as humans are diploid) the often cited human effective population size Ne of 10,000 individuals (e.g. Tenesa A, Navarro P, Hayes BJ, Duffy DL, Clarke GM, Goddard ME, Visscher PM. Recent human effective population size estimated from linkage disequilibrium. Genome Res. 2007 Apr;17(4):520-6. doi: 10.1101/gr.6023607). We did not explicitly estimate it.
Best, Benedikt.
