### ISSUE TITLE
Query Regarding Parameters in generating the lookup table

### ISSUE THREAD

**Issue by yunhanajing** [bekirsch/HaploBlocks#6]
I apologize for disturbing you again. I am very interested in your software. However, I have encountered some issues while generating the lookup table. I would like to know how to set the "--max_k" parameter when my chromosomes are X/Y. 
Additionally, According to the example command provided on your GitHub page: "../build/filter_lookup --N_e 2e4 --max_k 1006 > example.lookup", if my VCF file contains multiple chromosomes, such as chromosome 2, chromosome 3, and chromosome 4, with a sample size of 15, should the "--max_k" parameter be the sum of 2 * 15 + 3 * 15 + 4 * 15?
 I would appreciate your confirmation on this matter.

**Comment by bekirsch** [comment]
Hi yunhanajing,

the parameter --max_k specifies the number of haploid chromosomes. There are 503 diploid individuals in the example, so for autosomes --max_k is set to 2x503=1006. For X and Y chromosomes, you have to count - for humans basically max_k_X = 2*c_f + c_m, and max_k_Y = c_m, where c_m and c_f refer to the number of males and females in your dataset, respectively.

It makes no sense to analyse multiple chromosomes jointly, as haploblocks cannot stretch across different chromosomes. In any case, if your genomes are diploid, max_k should be set to 2*15. Also, note that 15 individuals is a rather small number: we assume that population frequencies can be sufficiently well estimated by sample frequencies. Although we appreciate your interest in our tool, we have to point out that for sample sizes that small, it may be worth checking out alternatives such as [CLUES](https://doi.org/10.1371/journal.pgen.1008384) or [SIA](https://doi.org/10.1093/molbev/msab332).



Stern AJ, Wilton PR, Nielsen R (2019) An approximate full-likelihood method for inferring selection and allele frequency trajectories from DNA sequence data. PLOS Genetics 15(9): e1008384. https://doi.org/10.1371/journal.pgen.1008384

Hussein A Hejase et al. (2022) A Deep-Learning Approach for Inference of Selective Sweeps from the Ancestral Recombination Graph, Molecular Biology and Evolution, Volume 39, Issue 1, msab332, https://doi.org/10.1093/molbev/msab332

**Comment by yunhanajing** [comment]
I sincerely apologize for causing you any inconvenience. I feel truly sorry. At the same time, I deeply appreciate your patient responses and valuable advice throughout
